/* Memories Unlocked account bridge — preserves existing anonymous memories and can safely copy them into an existing account. */
(function(){
const q=s=>document.querySelector(s);
const accountIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"></circle><path d="M4.5 21a7.5 7.5 0 0 1 15 0"></path></svg>';
function ensureUI(){if(q('#accountModal'))return;const btn=document.createElement('button');btn.className='account-trigger';btn.id='accountTrigger';btn.type='button';btn.innerHTML=accountIcon;btn.title='Account';btn.setAttribute('aria-label','Account');btn.onclick=openAccount;const actions=q('.header-actions');if(actions)actions.prepend(btn);const nav=q('.nav');if(nav&&!q('#accountNavTrigger')){const navBtn=document.createElement('button');navBtn.id='accountNavTrigger';navBtn.type='button';navBtn.className='account-nav-trigger';navBtn.innerHTML=accountIcon+'<span>Account</span>';navBtn.title='Account';navBtn.setAttribute('aria-label','Account');navBtn.onclick=openAccount;nav.appendChild(navBtn);}const modal=document.createElement('div');modal.id='accountModal';modal.className='modal';modal.innerHTML=`<div class="sheet account-sheet"><button class="close" onclick="closeAccount()">×</button><div class="welcome">YOUR MEMORIES, EVERYWHERE</div><h2>Account & Sync</h2><p class="intro">One account keeps your journeys and memories connected across your devices.</p><div id="accountState"></div></div>`;document.body.appendChild(modal);}
async function state(){const {data:{user}}=await muSupabase.auth.getUser();return user||null;}
function anonymousScreen(){return `<div class="account-choice account-primary"><div class="account-choice-icon">🔐</div><div><h3>Keep the memories already here</h3><p>This device currently owns your saved journeys. Create a new account here, or safely move them into an account you already have.</p></div><label>Email address</label><input id="claimEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Create password</label><input id="claimPassword" type="password" autocomplete="new-password" placeholder="At least 6 characters"><button class="save" onclick="claimAccount()">Create account & keep my memories</button></div><div class="account-divider"><span>ALREADY HAVE AN ACCOUNT?</span></div><div class="account-choice account-secondary"><h3>Move these memories into my existing account</h3><p>Use your existing Memories Unlocked sign-in. We copy the journeys and memories visible on this device into that account before reloading it.</p><label>Email address</label><input id="loginEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Existing account password</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="Your existing password"><button class="secondary" onclick="mergeExistingAccount()">Sign in & safely move these memories</button></div><p id="accountMessage" class="form-message"></p>`;}
window.openAccount=async function(){ensureUI();q('#accountModal').classList.add('open');q('#accountNavTrigger')?.classList.add('account-active');const user=await state();const box=q('#accountState');if(user&&!user.is_anonymous){box.innerHTML=`<div class="account-connected"><div class="account-state-icon">✓</div><strong>Your memories are synced</strong><p>${safe(user.email||'Your account')} is connected on this device.</p><button class="secondary" onclick="accountSignOut()">Sign out</button></div>`;return;}box.innerHTML=anonymousScreen();};
window.closeAccount=function(){q('#accountModal')?.classList.remove('open');q('#accountNavTrigger')?.classList.remove('account-active');};
window.claimAccount=async function(){const email=q('#claimEmail').value.trim(),password=q('#claimPassword').value,msg=q('#accountMessage');if(!email||password.length<6){msg.textContent='Enter your email and a password of at least 6 characters.';return;}msg.textContent='Creating your secure account…';const {data,error}=await muSupabase.auth.updateUser({email,password});if(error){if(/already.*registered|already.*exists|already been registered/i.test(error.message||'')){msg.textContent='That email already has an account. Use “Move these memories into my existing account” below with that account’s existing password.';}else msg.textContent=error.message;return;}if(data.user?.email_confirmed_at){msg.textContent='Account created. Reloading your synced memories…';setTimeout(()=>location.reload(),700);}else msg.textContent='Account created. Check your email if Supabase asks you to confirm the address, then return here.';};
async function insertWithOptionalFallback(table,row,optional){let current={...row};for(let attempt=0;attempt<=optional.length;attempt++){const result=await muSupabase.from(table).insert(current).select().single();if(!result.error)return result.data;const message=result.error.message||'';const missing=optional.find(name=>Object.prototype.hasOwnProperty.call(current,name)&&(message.includes(`'${name}'`)||message.includes(`\"${name}\"`)||message.includes(`.${name} `)));if(['PGRST204','42703'].includes(result.error.code)&&missing){delete current[missing];continue;}throw result.error;}throw new Error('Cloud copy could not be completed.');}
window.mergeExistingAccount=async function(){const email=q('#loginEmail').value.trim(),password=q('#loginPassword').value,msg=q('#accountMessage');if(!email||!password){msg.textContent='Enter the email and password for your existing account.';return;}const localJourneys=Array.isArray(window.journeys)?window.journeys.slice():JSON.parse(localStorage.getItem('mu_journeys')||'[]');const localMemories=Array.isArray(window.memories)?window.memories.slice():JSON.parse(localStorage.getItem('mu_memories')||'[]');if(!localJourneys.length&&!localMemories.length){msg.textContent='No memories are visible on this device to move. Nothing has been changed.';return;}msg.textContent='Protecting your current memories…';try{localStorage.setItem('mu_pre_account_merge_backup',JSON.stringify({saved_at:new Date().toISOString(),journeys:localJourneys,memories:localMemories}));}catch(e){}
msg.textContent='Signing into your existing account…';const {error:signError}=await muSupabase.auth.signInWithPassword({email,password});if(signError){msg.textContent='Sign-in failed: '+signError.message+'. Your existing memories are still saved on this device.';return;}const {data:{user}}=await muSupabase.auth.getUser();if(!user){msg.textContent='Could not confirm the account. Your local backup is unchanged.';return;}msg.textContent='Moving your journeys and memories safely…';try{const idMap=new Map();for(const j of localJourneys){const data=await insertWithOptionalFallback('journeys',{owner_id:user.id,title:j.title||'Untitled journey',story:j.story||'',location:j.location||'',start_date:j.start||null,end_date:j.end||null,visibility:String(j.privacy||'Private').toLowerCase(),share_code:j.code||null},['share_code']);idMap.set(String(j.id),data.id);}for(const m of localMemories){const newJourneyId=idMap.get(String(m.journeyId));if(!newJourneyId)continue;await insertWithOptionalFallback('memories',{owner_id:user.id,journey_id:newJourneyId,title:m.title||'Memory',story:m.story||'',location:m.location||'',memory_date:m.date||null,clue:m.clue||null,latitude:m.latitude??null,longitude:m.longitude??null},['clue','latitude','longitude']);}localStorage.removeItem('mu_journeys');localStorage.removeItem('mu_memories');msg.textContent='Done — your memories are now attached to your existing account. Reloading…';setTimeout(()=>location.reload(),900);}catch(error){msg.textContent='The move was not completed: '+error.message+'. Your local safety backup is still on this laptop. Do not add or delete anything yet.';}};
window.accountSignIn=async function(){const email=q('#loginEmail').value.trim(),password=q('#loginPassword').value,msg=q('#accountMessage');if(!email||!password){msg.textContent='Enter your email and password.';return;}const {error}=await muSupabase.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return;}setTimeout(()=>location.reload(),500);};
window.accountSignOut=async function(){await muSupabase.auth.signOut();location.reload();};
function safe(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.addEventListener('DOMContentLoaded',ensureUI);
})();