/* Memories Unlocked account bridge — upgrades an anonymous cloud user without changing its user id, preserving owned cloud data. */
(function(){
const q=s=>document.querySelector(s);
const accountIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"></circle><path d="M4.5 21a7.5 7.5 0 0 1 15 0"></path></svg>';
function ensureUI(){if(q('#accountModal'))return;const btn=document.createElement('button');btn.className='account-trigger';btn.id='accountTrigger';btn.type='button';btn.innerHTML=accountIcon;btn.title='Account';btn.setAttribute('aria-label','Account');btn.onclick=openAccount;const actions=q('.header-actions');if(actions)actions.prepend(btn);const nav=q('.nav');if(nav&&!q('#accountNavTrigger')){const navBtn=document.createElement('button');navBtn.id='accountNavTrigger';navBtn.type='button';navBtn.className='account-nav-trigger';navBtn.innerHTML=accountIcon+'<span>Account</span>';navBtn.title='Account';navBtn.setAttribute('aria-label','Account');navBtn.onclick=openAccount;nav.appendChild(navBtn);}const modal=document.createElement('div');modal.id='accountModal';modal.className='modal';modal.innerHTML=`<div class="sheet account-sheet"><button class="close" onclick="closeAccount()">×</button><div class="welcome">YOUR MEMORIES, EVERYWHERE</div><h2>Account & Sync</h2><p class="intro" id="accountIntro">One account keeps your journeys and memories connected across your devices.</p><div id="accountState"></div></div>`;document.body.appendChild(modal);}
async function state(){const {data:{user}}=await muSupabase.auth.getUser();return user||null;}
window.openAccount=async function(){ensureUI();q('#accountModal').classList.add('open');q('#accountNavTrigger')?.classList.add('account-active');const user=await state();const box=q('#accountState');if(user&&!user.is_anonymous){box.innerHTML=`<div class="account-connected"><div class="account-state-icon">✓</div><strong>Your memories are synced</strong><p>${safe(user.email||'Your account')} is connected on this device.</p><button class="secondary" onclick="accountSignOut()">Sign out</button></div>`;return;}box.innerHTML=`<div class="account-choice account-primary"><div class="account-choice-icon">🔐</div><div><h3>Keep the memories already here</h3><p>This is the right choice for the device that already holds your journeys. Creating your account here keeps those memories attached to you.</p></div><label>Email address</label><input id="claimEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Create password</label><input id="claimPassword" type="password" autocomplete="new-password" placeholder="At least 6 characters"><button class="save" onclick="claimAccount()">Create account & keep my memories</button></div><div class="account-divider"><span>ALREADY HAVE AN ACCOUNT?</span></div><div class="account-choice account-secondary"><h3>Sign in on another device</h3><p>Use this after creating your account on the device that already contains your memories.</p><label>Email address</label><input id="loginEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="Your password"><button class="secondary" onclick="accountSignIn()">Sign in & load my memories</button></div><p id="accountMessage" class="form-message"></p>`;};
window.closeAccount=function(){q('#accountModal')?.classList.remove('open');q('#accountNavTrigger')?.classList.remove('account-active');};
window.claimAccount=async function(){const email=q('#claimEmail').value.trim(),password=q('#claimPassword').value,msg=q('#accountMessage');if(!email||password.length<6){msg.textContent='Enter your email and a password of at least 6 characters.';return;}msg.textContent='Creating your secure account…';const {data,error}=await muSupabase.auth.updateUser({email,password});if(error){msg.textContent=error.message;return;}if(data.user?.email_confirmed_at){msg.textContent='Account created. Reloading your synced memories…';setTimeout(()=>location.reload(),700);}else msg.textContent='Account created. Check your email if Supabase asks you to confirm the address, then return here.';};
window.accountSignIn=async function(){const email=q('#loginEmail').value.trim(),password=q('#loginPassword').value,msg=q('#accountMessage');if(!email||!password){msg.textContent='Enter your email and password.';return;}msg.textContent='Signing in…';await muSupabase.auth.signOut();const {error}=await muSupabase.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return;}msg.textContent='Connected. Loading your memories…';setTimeout(()=>location.reload(),500);};
window.accountSignOut=async function(){await muSupabase.auth.signOut();location.reload();};
function safe(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.addEventListener('DOMContentLoaded',ensureUI);
})();