/* Memories Unlocked account bridge — upgrades an anonymous cloud user without changing its user id, preserving owned cloud data. */
(function(){
const q=s=>document.querySelector(s);
function ensureUI(){if(q('#accountModal'))return;const btn=document.createElement('button');btn.className='account-trigger';btn.id='accountTrigger';btn.type='button';btn.innerHTML='👤';btn.title='Account & sync';btn.setAttribute('aria-label','Account and sync');btn.onclick=openAccount;const actions=q('.header-actions');if(actions)actions.prepend(btn);const nav=q('.nav');if(nav&&!q('#accountNavTrigger')){const navBtn=document.createElement('button');navBtn.id='accountNavTrigger';navBtn.type='button';navBtn.className='account-nav-trigger';navBtn.innerHTML='<span class="account-nav-icon">👤</span><span>Account & Sync</span>';navBtn.title='Account & Sync';navBtn.setAttribute('aria-label','Account and Sync');navBtn.onclick=openAccount;nav.appendChild(navBtn);}const modal=document.createElement('div');modal.id='accountModal';modal.className='modal';modal.innerHTML=`<div class="sheet account-sheet"><button class="close" onclick="closeAccount()">×</button><div class="welcome">YOUR MEMORIES, EVERYWHERE</div><h2>Account & Sync</h2><p class="intro" id="accountIntro">Connect this device to your Memories Unlocked account.</p><div id="accountState"></div></div>`;document.body.appendChild(modal);}
async function state(){const {data:{user}}=await muSupabase.auth.getUser();return user||null;}
window.openAccount=async function(){ensureUI();q('#accountModal').classList.add('open');const user=await state();const box=q('#accountState');if(user&&!user.is_anonymous){box.innerHTML=`<div class="account-connected"><strong>☁️ Synced account</strong><p>${safe(user.email||'Your account')} is connected on this device.</p><button class="secondary" onclick="accountSignOut()">Sign out</button></div>`;return;}box.innerHTML=`<div class="account-choice"><h3>Keep the memories on this device</h3><p>If this device already contains your journeys, create your account here first. Your existing cloud ownership stays attached to the same user.</p><input id="claimEmail" type="email" autocomplete="email" placeholder="Email address"><input id="claimPassword" type="password" autocomplete="new-password" placeholder="Create password (6+ characters)"><button class="save" onclick="claimAccount()">Create & sync my account</button></div><div class="account-divider"><span>OR</span></div><div class="account-choice"><h3>I already created my account</h3><p>Use this on your other phone, tablet or computer.</p><input id="loginEmail" type="email" autocomplete="email" placeholder="Email address"><input id="loginPassword" type="password" autocomplete="current-password" placeholder="Password"><button class="secondary" onclick="accountSignIn()">Sign in & load my memories</button></div><p id="accountMessage" class="form-message"></p>`;};
window.closeAccount=function(){q('#accountModal')?.classList.remove('open');};
window.claimAccount=async function(){const email=q('#claimEmail').value.trim(),password=q('#claimPassword').value,msg=q('#accountMessage');if(!email||password.length<6){msg.textContent='Enter your email and a password of at least 6 characters.';return;}msg.textContent='Creating your secure account…';const {data,error}=await muSupabase.auth.updateUser({email,password});if(error){msg.textContent=error.message;return;}if(data.user?.email_confirmed_at){msg.textContent='Account created. Reloading your synced memories…';setTimeout(()=>location.reload(),700);}else msg.textContent='Account created. Check your email if Supabase asks you to confirm the address, then return here.';};
window.accountSignIn=async function(){const email=q('#loginEmail').value.trim(),password=q('#loginPassword').value,msg=q('#accountMessage');if(!email||!password){msg.textContent='Enter your email and password.';return;}msg.textContent='Signing in…';await muSupabase.auth.signOut();const {error}=await muSupabase.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return;}msg.textContent='Connected. Loading your memories…';setTimeout(()=>location.reload(),500);};
window.accountSignOut=async function(){await muSupabase.auth.signOut();location.reload();};
function safe(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.addEventListener('DOMContentLoaded',ensureUI);
})();