const JKEY='mu_journeys',MKEY='mu_memories';
let journeys=[],memories=[];
try{journeys=JSON.parse(localStorage.getItem(JKEY)||'[]');memories=JSON.parse(localStorage.getItem(MKEY)||'[]')}catch(e){journeys=[];memories=[]}
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openModal(id){const el=$(id);if(el)el.classList.add('open')}
function closeModal(id){const el=$(id);if(el)el.classList.remove('open')}
function save(){localStorage.setItem(JKEY,JSON.stringify(journeys));localStorage.setItem(MKEY,JSON.stringify(memories))}
function showView(id){const target=$(id);if(!target)return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));target.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});render()}
function createJourney(){const title=$('title').value.trim(),location=$('location').value.trim();if(!title||!location){alert('Add a journey name and location.');return}const now=Date.now();journeys.unshift({id:now,title,location,story:$('story').value.trim(),start:$('startDate').value,end:$('endDate').value,privacy:$('privacy').value,code:title.replace(/[^a-z0-9]/gi,'').slice(0,5).toUpperCase()+'-'+String(now).slice(-4)});save();closeModal('journeyModal');['title','location','story','startDate','endDate'].forEach(x=>$(x).value='');render();showView('journeys')}
function fillJourneys(){const select=$('memoryJourney');if(!select)return;select.innerHTML=journeys.map(j=>`<option value="${j.id}">${esc(j.title)} — ${esc(j.location)}</option>`).join('')}
function addMemory(journeyId){if(!journeys.length){alert('Create a journey first.');openModal('journeyModal');return}fillJourneys();if(journeyId&&$('memoryJourney'))$('memoryJourney').value=String(journeyId);openModal('memoryModal')}
function createMemory(){const title=$('memoryTitle').value.trim(),location=$('memoryLocation').value.trim(),journeyId=Number($('memoryJourney').value);if(!journeyId){alert('Choose a journey.');return}if(!title||!location){alert('Add a memory title and location.');return}memories.unshift({id:Date.now(),journeyId,title,location,date:$('memoryDate').value,story:$('memoryStory').value.trim(),clue:$('memoryClue').value.trim()});save();closeModal('memoryModal');['memoryTitle','memoryLocation','memoryDate','memoryStory','memoryClue'].forEach(x=>$(x).value='');render();showView('journeys')}
function card(j){const ms=memories.filter(m=>Number(m.journeyId)===Number(j.id));return `<article class="journey"><div class="hero"><small>${esc(j.location)} · ${j.start?esc(j.start.slice(0,4)):'Journey'}</small><h3>${esc(j.title)}</h3></div><div class="body"><p>${esc(j.story)||'Your story starts here.'}</p><div><span class="pill">🔒 ${esc(j.privacy||'Private')}</span><span class="pill">Code ${esc(j.code)}</span></div>${ms.map(m=>`<div class="memory"><b>📍 ${esc(m.title)}</b><br>${esc(m.location)}${m.date?'<br><small>'+esc(m.date)+'</small>':''}${m.story?'<br>'+esc(m.story):''}${m.clue?'<br><small>🔐 '+esc(m.clue)+'</small>':''}</div>`).join('')}<button class="save" onclick="addMemory(${Number(j.id)})">＋ Add a Memory to this Journey</button></div></article>`}
function render(){const jl=$('journeyList'),aj=$('allJourneys'),rm=$('recentMemories'),mp=$('mapPins');if(jl)jl.innerHTML=journeys.length?journeys.slice(0,3).map(card).join(''):'<div class="empty">No journeys yet. Tap <b>Create Journey</b> to begin.</div>';if(aj)aj.innerHTML=journeys.length?journeys.map(card).join(''):'<div class="empty">Your journeys will appear here.</div>';if(rm)rm.innerHTML=memories.length?`<div class="journey"><div class="body">${memories.slice(0,5).map(m=>`<div class="memory"><b>📍 ${esc(m.title)}</b> — ${esc(m.location)}<br><small>${esc(m.date)||'A memory worth keeping'}</small></div>`).join('')}</div></div>`:'<div class="empty">Your pinned memories will appear here.</div>';if(mp)mp.innerHTML=memories.length?memories.map(m=>`<div class="pin">📍 <b>${esc(m.location)}</b><br><small>${esc(m.title)}</small></div>`).join(''):'<div class="empty">Your map is waiting for its first memory pin.</div>';if(journeys.length)fillJourneys()}
function followJourney(){const code=$('followCode').value.trim().toUpperCase(),j=journeys.find(x=>String(x.code||'').toUpperCase()===code),msg=$('followMessage');if(!msg)return;msg.innerHTML=j?`🔓 Unlocked: <b>${esc(j.title)}</b> — ${esc(j.location)}`:'That journey is not stored on this device yet. Cloud sharing comes next.'}
document.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.target.classList.remove('open')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'))});
render();