const JKEY='mu_journeys',MKEY='mu_memories';let journeys=JSON.parse(localStorage.getItem(JKEY)||'[]'),memories=JSON.parse(localStorage.getItem(MKEY)||'[]');
const $=id=>document.getElementById(id);const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openModal(id){$(id).classList.add('open')}function closeModal(id){$(id).classList.remove('open')}function save(){localStorage.setItem(JKEY,JSON.stringify(journeys));localStorage.setItem(MKEY,JSON.stringify(memories))}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');render()}
function createJourney(){let title=$('title').value.trim(),location=$('location').value.trim();if(!title||!location)return alert('Add a journey name and location.');journeys.unshift({id:Date.now(),title,location,story:$('story').value.trim(),start:$('startDate').value,end:$('endDate').value,privacy:$('privacy').value,code:title.replace(/[^a-z0-9]/gi,'').slice(0,5).toUpperCase()+'-'+String(Date.now()).slice(-4)});save();closeModal('journeyModal');['title','location','story','startDate','endDate'].forEach(x=>$(x).value='');render()}
function addMemory(){if(!journeys.length){alert('Create a journey first.');return openModal('journeyModal')}fillJourneys();openModal('memoryModal')}
function fillJourneys(){$('memoryJourney').innerHTML=journeys.map(j=>`<option value="${j.id}">${esc(j.title)}</option>`).join('')}
function createMemory(){let title=$('memoryTitle').value.trim(),location=$('memoryLocation').value.trim();if(!title||!location)return alert('Add a memory title and location.');memories.unshift({id:Date.now(),journeyId:Number($('memoryJourney').value),title,location,date:$('memoryDate').value,story:$('memoryStory').value.trim(),clue:$('memoryClue').value.trim()});save();closeModal('memoryModal');['memoryTitle','memoryLocation','memoryDate','memoryStory','memoryClue'].forEach(x=>$(x).value='');render()}
function card(j){let ms=memories.filter(m=>m.journeyId===j.id);return `<article class="journey"><div class="hero"><small>${esc(j.location)} · ${j.start?j.start.slice(0,4):'Journey'}</small><h3>${esc(j.title)}</h3></div><div class="body">${esc(j.story)||'Your story starts here.'}<div><span class="pill">🔒 ${esc(j.privacy)}</span><span class="pill">Code ${j.code}</span></div>${ms.map(m=>`<div class="memory"><b>📍 ${esc(m.title)}</b><br>${esc(m.location)}${m.story?'<br>'+esc(m.story):''}${m.clue?'<br><small>🔐 '+esc(m.clue)+'</small>':''}</div>`).join('')}</div></article>`}
function render(){$('journeyList').innerHTML=journeys.length?journeys.slice(0,3).map(card).join(''):'<div class="empty">No journeys yet. Tap <b>Create Journey</b> to begin.</div>';$('allJourneys').innerHTML=journeys.length?journeys.map(card).join(''):'<div class="empty">Your journeys will appear here.</div>';$('recentMemories').innerHTML=memories.length?`<div class="journey"><div class="body">${memories.slice(0,5).map(m=>`<div class="memory"><b>📍 ${esc(m.title)}</b> — ${esc(m.location)}<br><small>${m.date||'A memory worth keeping'}</small></div>`).join('')}</div></div>`:'<div class="empty">Your pinned memories will appear here.</div>';$('mapPins').innerHTML=memories.length?memories.map(m=>`<div class="pin">📍 <b>${esc(m.location)}</b><br><small>${esc(m.title)}</small></div>`).join(''):'<div class="empty">Your map is waiting for its first memory pin.</div>';if(journeys.length)fillJourneys()}
function followJourney(){let code=$('followCode').value.trim().toUpperCase(),j=journeys.find(x=>x.code===code);$('followMessage').innerHTML=j?`🔓 Unlocked: <b>${esc(j.title)}</b> — ${esc(j.location)}`:'That journey is not stored on this device yet. Cloud sharing comes next.'}
render();