let deferredInstallPrompt=null;
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;}
function markStandalone(){const standalone=isStandalone();document.documentElement.classList.toggle('standalone-app',standalone);document.querySelectorAll('[data-install-app]').forEach(el=>{if(standalone)el.hidden=true;});return standalone;}
function pwaPlatform(){const ua=navigator.userAgent||'';if(/iphone|ipad|ipod/i.test(ua))return'ios';if(/android/i.test(ua))return'android';if(/windows/i.test(ua))return'windows';return'desktop';}
function installHelp(){if(isStandalone()){toast('Memories Unlocked is already installed on this device.');return;}const platform=pwaPlatform();let steps='Use your browser menu and choose Install app or Create shortcut.';if(platform==='ios')steps='In Safari, tap the Share button, choose Add to Home Screen, then tap Add.';if(platform==='android')steps='In Chrome, open the menu (⋮), choose Install app or Add to Home screen, then confirm.';if(platform==='windows')steps='In Edge or Chrome, use the Install icon in the address bar or open the browser menu and choose Install Memories Unlocked.';mountDialog('installModal',`<button class="close" onclick="closeModal('installModal')">×</button><div class="welcome">TAKE YOUR MEMORIES WITH YOU</div><h2>Install Memories Unlocked</h2><p class="intro">Open your journeys from your home screen like an app.</p><div class="install-steps"><strong>${esc(steps)}</strong><p class="small">Once installed, Memories Unlocked opens in its own app window. The app shell can start offline; cloud memories refresh when you are connected.</p></div>${deferredInstallPrompt?'<button class="save" onclick="installMemoriesUnlocked()">Install Memories Unlocked</button>':''}<button class="secondary" onclick="closeModal('installModal')">Not now</button>`,'install-panel');}
async function installMemoriesUnlocked(){if(!deferredInstallPrompt){installHelp();return;}deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;closeModal('installModal');if(choice.outcome==='accepted')toast('Memories Unlocked is being added to your device.');}
function loadDuplicateV2(){if(document.querySelector('script[data-mu-duplicate-v2]'))return;const script=document.createElement('script');script.src='/duplicate-detection-v2.js?v=20260915a';script.dataset.muDuplicateV2='1';document.body.appendChild(script);}
function loadSyncHardening(){if(document.querySelector('script[data-mu-sync-hardening]')){loadDuplicateV2();return;}const script=document.createElement('script');script.src='/sync-hardening.js?v=20260914-rome-diagnostics-2';script.async=false;script.dataset.muSyncHardening='1';script.onload=()=>{console.info('Memories Unlocked sync hardening loaded');loadDuplicateV2();};script.onerror=()=>{console.error('Memories Unlocked sync hardening failed to load');loadDuplicateV2();};document.body.appendChild(script);}
function loadAccountBridge(){if(!document.querySelector('link[data-mu-account]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/account.css';link.dataset.muAccount='1';document.head.appendChild(link);}if(!document.querySelector('script[data-mu-account],script[src="/account.js"],script[src$="account.js"]')){const script=document.createElement('script');script.src='/account.js';script.defer=true;script.dataset.muAccount='1';script.onload=loadSyncHardening;document.body.appendChild(script);}else loadSyncHardening();}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;if(!markStandalone())document.querySelectorAll('[data-install-app]').forEach(el=>el.hidden=false);});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;markStandalone();toast('Memories Unlocked is installed. Your journeys are now one tap away.');});
window.addEventListener('DOMContentLoaded',async()=>{if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('/sw.js?v=20260918rc3',{updateViaCache:'none'});reg.update().catch(()=>{});}catch{}}const standalone=markStandalone();if(!standalone&&pwaPlatform()==='ios')document.querySelectorAll('[data-install-app]').forEach(el=>el.hidden=false);loadAccountBridge();});
const displayModeQuery=window.matchMedia('(display-mode: standalone)');if(displayModeQuery.addEventListener)displayModeQuery.addEventListener('change',markStandalone);