// Optional isolated PostgreSQL check; does not contact the live Supabase project.
const {PGlite}=require(process.env.MEMORIES_PGLITE_MODULE || '@electric-sql/pglite');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 const j='11111111-1111-4111-8111-111111111111';
 await db.exec(`create role anon nologin; create role authenticated nologin; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to anon,authenticated;
 insert into auth.users values ('${a}'),('${b}');`);
 const migration=fs.readFileSync(path.join(__dirname,'../supabase/001_private_collection.sql'),'utf8');
 await db.exec(migration);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${a}';`);
 await db.query('insert into journeys(id,title,start_date,end_date) values ($1,$2,$3,$4)',[j,'Rome','1998-03-20','1998-03-21']);
 assert.equal((await db.query('select * from journeys')).rows.length,1);
 await assert.rejects(db.query('insert into journeys(title,owner_id) values ($1,$2)',['Spoof',b]),/row-level security/);
 await assert.rejects(db.query("insert into journeys(title,start_date,end_date) values ('Bad dates','2026-02-02','2026-01-01')"),/check constraint/);
 await db.query('insert into memories(journey_id,title,story) values ($1,$2,$3)',[j,'A moment','Our story']);
 await db.exec(`set request.jwt.claim.sub='${b}';`);
 assert.equal((await db.query('select * from journeys')).rows.length,0);
 assert.equal((await db.query('select * from memories')).rows.length,0);
 await assert.rejects(db.query('insert into memories(journey_id,title,story) values ($1,$2,$3)',[j,'Wrong owner','Should fail']),/foreign key/);
 await db.exec('reset role; set role anon;');
 await assert.rejects(db.query('select * from journeys'),/permission denied/);
 await assert.rejects(db.query("insert into journeys(title) values ('Anonymous')"),/permission denied/);
 await db.exec('reset role;');
 await assert.rejects(db.exec(migration),/already exists/);
 await db.exec('rollback;');
 assert.equal((await db.query('select * from journeys')).rows.length,1);
 assert.equal((await db.query('select * from memories')).rows.length,1);
 const editing=fs.readFileSync(path.join(__dirname,'../supabase/002_owner_editing.sql'),'utf8');
 await db.exec(editing);await db.exec(editing);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${a}';`);
 assert.equal((await db.query('update journeys set title=$1 where id=$2 returning title',['Edited',j])).rows[0].title,'Edited');
 assert.equal((await db.query('update memories set story=$1 where journey_id=$2 returning story',['Edited story',j])).rows[0].story,'Edited story');
 await assert.rejects(db.query('update journeys set owner_id=$1 where id=$2',[b,j]),/permission denied/);
 await assert.rejects(db.query("update journeys set visibility='public' where id=$1",[j]),/permission denied/);
 await assert.rejects(db.query('update memories set journey_id=$1',[j]),/permission denied/);
 await assert.rejects(db.query("update journeys set start_date='2026-02-02',end_date='2026-01-01' where id=$1",[j]),/check constraint/);
 await db.exec(`set request.jwt.claim.sub='${b}';`);
 assert.equal((await db.query("update journeys set title='Not mine' where id=$1 returning id",[j])).rows.length,0);
 assert.equal((await db.query("update memories set story='Not mine' returning id")).rows.length,0);
 await db.exec('reset role; set role anon;');
 await assert.rejects(db.query("update journeys set title='Anonymous'"),/permission denied/);
 await db.exec('reset role;');
 assert.equal((await db.query('select title from journeys')).rows[0].title,'Edited');
 await db.close();
 console.log('PASS: creation and editing migrations, owner isolation, spoof/ownership/reparenting rejection, date constraints, anonymous denial and safe reruns.');
})().catch(error=>{console.error(error);process.exitCode=1;});
